# vars loading order: common_config -> this file
mysqlshell_version: 8.0.34

# The following vars are not recommended to be modified.
mysqlshell_base_dir: /database/mysqlshell/{{ mysqlshell_version }}
mysql_shell_package_name: "mysql-shell-{{ mysqlshell_version }}-linux-glibc2.12-x86-64bit.tar.gz"
mysql_shell_package_path: "{{ mysql_packages_dir }}/{{ mysql_shell_package_name }}"
mysql_shell_download_url: "https://dev.mysql.com/get/Downloads/MySQL-Shell/{{ mysql_shell_package_name }}"
