import { PageHeader, StatusPill, TechCard } from "@/components/Blueprint";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Database, Loader2, Plus, ServerCog } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";

const engineLabels: Record<string, string> = { mysql: "MySQL", postgresql: "PostgreSQL", oracle: "Oracle", sql_server: "SQL Server", dameng: "达梦", kingbase: "金仓", oceanbase: "OceanBase", polardb: "PolarDB", gaussdb: "GaussDB", tidb: "TiDB", goldendb: "GoldenDB", gbase: "GBase", tdsql: "TDSQL", opengauss: "openGauss" };
const engines = Object.keys(engineLabels);

export default function Assets() {
  const utils = trpc.useUtils();
  const assets = trpc.ops.assets.list.useQuery();
  const [engineFilter, setEngineFilter] = useState("all");
  const [environmentFilter, setEnvironmentFilter] = useState("all");
  const [healthFilter, setHealthFilter] = useState("all");
  const [selectedAssetId, setSelectedAssetId] = useState<number | undefined>();
  const [isCreating, setCreating] = useState(false);
  const [form, setForm] = useState({ name: "", engine: "mysql", host: "", port: "3306", databaseName: "", version: "", environment: "production", owner: "", credentialRef: "", tags: "" });
  const create = trpc.ops.assets.create.useMutation({ onSuccess: () => { toast.success("数据库资产已登记"); setCreating(false); setForm({ name: "", engine: "mysql", host: "", port: "3306", databaseName: "", version: "", environment: "production", owner: "", credentialRef: "", tags: "" }); utils.ops.assets.list.invalidate(); utils.ops.overview.invalidate(); }, onError: error => toast.error(error.message) });
  const list = useMemo(() => (assets.data ?? []).filter(item => (engineFilter === "all" || item.engine === engineFilter) && (environmentFilter === "all" || item.environment === environmentFilter) && (healthFilter === "all" || item.healthStatus === healthFilter)), [assets.data, engineFilter, environmentFilter, healthFilter]);
  const selectedAsset = (assets.data ?? []).find(item => item.id === selectedAssetId);
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate({ ...form, engine: form.engine as never, environment: form.environment as never, port: Number(form.port), tags: form.tags.split(",").map(item => item.trim()).filter(Boolean), capabilities: [] }); };

  return <div className="mx-auto max-w-[1600px] space-y-6">
    <PageHeader eyebrow="ASSET REGISTRY · A01" title="数据库实例资产中心" description="统一登记连接端点、版本、环境、资产责任人与健康上下文。凭据仅以受控密钥引用保存，不会写入控制面数据库。" action={<Button onClick={() => setCreating(value => !value)} className="gap-2 bg-cyan-200 text-[#061b51] hover:bg-cyan-100"><Plus className="h-4 w-4" />{isCreating ? "收起登记表" : "登记实例"}</Button>} />
    {isCreating ? <TechCard label="REGISTER INSTANCE"><form onSubmit={submit} className="grid gap-4 lg:grid-cols-4"><Field label="实例名称" value={form.name} onChange={value => setForm({ ...form, name: value })} placeholder="例如：finance-mysql-prod" required /><Select label="数据库类型" value={form.engine} onChange={value => setForm({ ...form, engine: value })}>{engines.map(key => <option key={key} value={key}>{engineLabels[key]}</option>)}</Select><Field label="主机 / 地址" value={form.host} onChange={value => setForm({ ...form, host: value })} placeholder="10.0.0.12 或 FQDN" required /><Field label="端口" value={form.port} onChange={value => setForm({ ...form, port: value })} type="number" required /><Field label="库名 / 服务名" value={form.databaseName} onChange={value => setForm({ ...form, databaseName: value })} placeholder="可选" /><Field label="版本" value={form.version} onChange={value => setForm({ ...form, version: value })} placeholder="例如：8.0.36" /><Select label="环境" value={form.environment} onChange={value => setForm({ ...form, environment: value })}><option value="production">生产</option><option value="staging">预发</option><option value="test">测试</option><option value="development">开发</option></Select><Field label="资产负责人" value={form.owner} onChange={value => setForm({ ...form, owner: value })} placeholder="姓名或团队" /><Field label="凭据引用" value={form.credentialRef} onChange={value => setForm({ ...form, credentialRef: value })} placeholder="例如：vault://db/prod/finance" /><div className="lg:col-span-2"><Field label="标签" value={form.tags} onChange={value => setForm({ ...form, tags: value })} placeholder="业务系统, 核心, 华北一区（逗号分隔）" /></div><div className="flex items-end"><Button disabled={create.isPending} type="submit" className="w-full gap-2 bg-cyan-200 text-[#061b51] hover:bg-cyan-100">{create.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <ServerCog className="h-4 w-4" />}安全登记</Button></div></form></TechCard> : null}
    <TechCard label="INVENTORY">
      <div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-display text-lg font-semibold text-white">已登记实例</h2><p className="mt-1 text-xs text-blue-100/55">按类型、环境与健康状态筛选，点击“详情”查看完整运维上下文。</p></div><div className="flex flex-wrap gap-2"><select aria-label="按数据库类型筛选" value={engineFilter} onChange={event => setEngineFilter(event.target.value)} className="mono h-9 border border-blue-200/20 bg-[#071e57] px-3 text-xs text-blue-50 outline-none"><option value="all">全部数据库类型</option>{engines.map(key => <option key={key} value={key}>{engineLabels[key]}</option>)}</select><select aria-label="按环境筛选" value={environmentFilter} onChange={event => setEnvironmentFilter(event.target.value)} className="mono h-9 border border-blue-200/20 bg-[#071e57] px-3 text-xs text-blue-50 outline-none"><option value="all">全部环境</option><option value="production">生产</option><option value="staging">预发</option><option value="test">测试</option><option value="development">开发</option></select><select aria-label="按健康状态筛选" value={healthFilter} onChange={event => setHealthFilter(event.target.value)} className="mono h-9 border border-blue-200/20 bg-[#071e57] px-3 text-xs text-blue-50 outline-none"><option value="all">全部健康状态</option><option value="healthy">健康</option><option value="warning">预警</option><option value="critical">严重</option><option value="unknown">未知</option></select></div></div>
      <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[970px] text-left"><thead className="mono border-y border-blue-300/15 text-[10px] uppercase tracking-[.12em] text-blue-100/45"><tr><th className="px-3 py-3 font-medium">实例 / 端点</th><th className="px-3 py-3 font-medium">类型 / 版本</th><th className="px-3 py-3 font-medium">环境</th><th className="px-3 py-3 font-medium">健康</th><th className="px-3 py-3 font-medium">容量</th><th className="px-3 py-3 font-medium">凭据边界</th><th className="px-3 py-3 text-right font-medium">详情</th></tr></thead><tbody>{list.map(item => <tr key={item.id} className="border-b border-blue-300/10 text-sm text-blue-50"><td className="px-3 py-4"><p className="font-medium text-white">{item.name}</p><p className="mono mt-1 text-[10px] text-blue-100/50">{item.host}:{item.port}{item.databaseName ? ` / ${item.databaseName}` : ""}</p></td><td className="px-3 py-4"><p>{engineLabels[item.engine] ?? item.engine}</p><p className="mono mt-1 text-[10px] text-blue-100/50">{item.version ?? "版本待采集"}</p></td><td className="px-3 py-4"><span className="mono text-xs text-cyan-100">{item.environment}</span></td><td className="px-3 py-4"><StatusPill status={item.healthStatus} /><p className="mono mt-1 text-[10px] text-blue-100/50">SCORE {item.healthScore}</p></td><td className="px-3 py-4">{item.capacityGb ? <><p>{item.usedCapacityGb ?? 0} / {item.capacityGb} GB</p><p className="mono mt-1 text-[10px] text-blue-100/50">{Math.round(((item.usedCapacityGb ?? 0) / item.capacityGb) * 100)}% USED</p></> : <span className="text-blue-100/40">待采集</span>}</td><td className="px-3 py-4"><span className="mono text-[10px] text-blue-100/55">{item.credentialRef ?? "未关联"}</span></td><td className="px-3 py-4 text-right"><Button size="sm" variant="outline" onClick={() => setSelectedAssetId(item.id)} className="h-8 border-blue-200/25 text-blue-50 hover:bg-blue-200/10">查看</Button></td></tr>)}{!list.length ? <tr><td colSpan={7} className="py-16 text-center"><Database className="mx-auto h-6 w-6 text-cyan-200/50" /><p className="mt-3 text-sm text-blue-100/55">尚未登记符合条件的数据库实例。</p></td></tr> : null}</tbody></table></div>
      {selectedAsset ? <div className="mt-5 border-t border-blue-300/15 pt-5"><div className="flex items-center justify-between"><div><p className="mono text-[10px] tracking-[.14em] text-cyan-200">INSTANCE DETAIL · {selectedAsset.id}</p><h3 className="mt-1 font-display text-lg font-semibold text-white">{selectedAsset.name}</h3></div><Button size="sm" variant="outline" onClick={() => setSelectedAssetId(undefined)} className="border-blue-200/25 text-blue-50">关闭</Button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Detail label="连接状态" value={selectedAsset.connectionStatus} /><Detail label="资产负责人" value={selectedAsset.owner ?? "未指定"} /><Detail label="最后检查" value={selectedAsset.lastCheckedAt ? new Date(selectedAsset.lastCheckedAt).toLocaleString() : "尚未检查"} /><Detail label="能力标签" value={(selectedAsset.capabilities ?? []).join(" · ") || "待节点上报"} /><Detail label="业务标签" value={(selectedAsset.tags ?? []).join(" · ") || "未配置"} /><Detail label="凭据引用" value={selectedAsset.credentialRef ?? "未关联"} /><Detail label="数据库类型" value={`${engineLabels[selectedAsset.engine] ?? selectedAsset.engine} ${selectedAsset.version ?? ""}`} /><Detail label="端点" value={`${selectedAsset.host}:${selectedAsset.port}${selectedAsset.databaseName ? ` / ${selectedAsset.databaseName}` : ""}`} /></div></div> : null}
    </TechCard>
  </div>;
}

function Field({ label, value, onChange, placeholder, required, type = "text" }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; required?: boolean; type?: string }) { return <label className="block"><span className="mono text-[10px] uppercase tracking-[.12em] text-blue-100/55">{label}</span><Input value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} type={type} required={required} className="mt-1.5 border-blue-200/20 bg-[#071e57] text-blue-50 placeholder:text-blue-100/30" /></label>; }
function Select({ label, value, onChange, children }: { label: string; value: string; onChange: (value: string) => void; children: React.ReactNode }) { return <label className="block"><span className="mono text-[10px] uppercase tracking-[.12em] text-blue-100/55">{label}</span><select value={value} onChange={event => onChange(event.target.value)} className="mt-1.5 h-9 w-full border border-blue-200/20 bg-[#071e57] px-3 text-sm text-blue-50 outline-none">{children}</select></label>; }
function Detail({ label, value }: { label: string; value: string }) { return <div className="border-l border-cyan-200/30 px-3"><p className="mono text-[10px] tracking-[.12em] text-cyan-200">{label}</p><p className="mt-1.5 break-all text-xs leading-5 text-blue-100/70">{value}</p></div>; }
