import { PageHeader, TechCard } from "@/components/Blueprint";
import { trpc } from "@/lib/trpc";
import { Check, CircleDashed, ShieldCheck } from "lucide-react";

const columns = [{ key: "deployment", label: "部署" }, { key: "backupRecovery", label: "备份恢复" }, { key: "inspection", label: "性能巡检" }, { key: "selfHealing", label: "故障自愈" }] as const;

export default function Capabilities() {
  const catalog = trpc.ops.catalog.useQuery();
  return <div className="mx-auto max-w-[1600px] space-y-6"><PageHeader eyebrow="ADAPTER BLUEPRINT · M01" title="多数据库适配能力矩阵" description="以统一的任务参数、风险策略和结果协议屏蔽数据库差异；受控执行节点按声明能力接管已批准的生产动作。" />
    <div className="grid gap-4 xl:grid-cols-[.75fr_1.25fr]"><TechCard label="EXECUTION GATEWAY"><h2 className="font-display text-lg font-semibold text-white">受控执行架构</h2><ol className="mt-5 space-y-4">{[["01","控制面创建执行单","资产、Runbook、审批、审计与策略在平台侧完成。"],["02","执行节点拉取任务","节点使用注册身份、任务签名与短时确认令牌拉取已批准任务。"],["03","适配器调用厂商能力","节点通过数据库驱动、受限 SSH 或厂商工具执行，并在本地脱敏日志。"],["04","结果与证据回传","控制面接收状态、结构化结果和日志摘要，形成可审计闭环。"]].map(([step,title,description]) => <li key={step} className="grid grid-cols-[34px_1fr] gap-3 border-l border-blue-300/20 pl-3"><span className="mono text-xs text-cyan-200">{step}</span><div><p className="text-sm text-white">{title}</p><p className="mt-1 text-xs leading-5 text-blue-100/55">{description}</p></div></li>)}</ol><div className="mt-6 border-t border-blue-300/12 pt-4 text-xs leading-5 text-blue-100/55"><ShieldCheck className="mr-2 inline h-4 w-4 text-cyan-200" />凭据使用密钥引用与执行节点本地代理，控制面不保存明文数据库密码。</div></TechCard>
      <TechCard label="CAPABILITY MATRIX"><div className="flex items-end justify-between gap-4"><div><h2 className="font-display text-lg font-semibold text-white">数据库引擎支持范围</h2><p className="mt-1 text-xs text-blue-100/55">矩阵定义任务可被编排的能力；具体执行仍受节点已声明的驱动与工具约束。</p></div><p className="mono text-xs text-cyan-200">{catalog.data?.adapters.length ?? 0} ENGINE TYPES</p></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[690px]"><thead className="mono border-y border-blue-300/15 text-[10px] uppercase tracking-[.12em] text-blue-100/45"><tr><th className="px-3 py-3 text-left font-medium">数据库</th><th className="px-3 py-3 text-left font-medium">分类</th>{columns.map(column => <th key={column.key} className="px-3 py-3 text-center font-medium">{column.label}</th>)}</tr></thead><tbody>{(catalog.data?.adapters ?? []).map(item => <tr key={item.engine} className="border-b border-blue-300/10 text-sm"><td className="px-3 py-3 text-white">{item.label}<p className="mono mt-1 text-[10px] text-blue-100/45">{item.engine}</p></td><td className="px-3 py-3 text-xs text-blue-100/65">{item.tier}</td>{columns.map(column => <td key={column.key} className="px-3 py-3 text-center">{item[column.key] ? <Check className="mx-auto h-4 w-4 text-cyan-200" /> : <CircleDashed className="mx-auto h-4 w-4 text-blue-100/25" />}</td>)}</tr>)}</tbody></table></div></TechCard></div>
    <TechCard label="STANDARD CONTRACT"><div className="grid gap-4 md:grid-cols-3">{[["输入","目标实例、Runbook 参数、风险级别、变更窗口、确认令牌"],["执行","节点能力声明、适配器操作、幂等标识、受限命令白名单"],["结果","状态、证据摘要、日志级别、耗时、回滚建议与追踪标识"]].map(([title,body]) => <div key={title} className="border-l border-cyan-200/35 px-4"><p className="mono text-[10px] tracking-[.15em] text-cyan-200">{title}</p><p className="mt-2 text-sm leading-6 text-blue-100/70">{body}</p></div>)}</div></TechCard>
  </div>;
}
