import { PageHeader, TechCard } from "@/components/Blueprint";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Bot, BrainCircuit, CheckCircle2, Loader2, ShieldAlert, Sparkles } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

type Analysis = { rootCause: string; confidence: number; impact: string; risk: string; evidence: string[]; recommendations: string[]; runbookDraft: { title: string; category: "deployment" | "backup_recovery" | "inspection" | "self_healing"; riskLevel: "low" | "medium" | "high" | "critical"; approvalRequired: boolean; compatibleEngines: string[]; parameters: Record<string, unknown>; steps: { name: string; action: string; requiresConfirmation: boolean }[] }; requiresHumanConfirmation: boolean };

export default function Intelligence() {
  const assets = trpc.ops.assets.list.useQuery(); const alerts = trpc.ops.alerts.list.useQuery(); const [context, setContext] = useState(""); const [instanceId, setInstanceId] = useState(""); const [alertId, setAlertId] = useState(""); const [result, setResult] = useState<Analysis | undefined>();
  const analyze = trpc.ops.intelligence.analyze.useMutation({ onSuccess: response => { setResult(response.result as Analysis); toast.success("智能诊断已生成结构化建议"); }, onError: error => toast.error(error.message) });
  const createRunbook = trpc.ops.runbooks.create.useMutation({ onSuccess: () => toast.success("结构化 Runbook 已创建为可执行状态，可在 Runbook 中心直接发起执行"), onError: error => toast.error(error.message) });
  const submit = () => { if (context.trim().length < 20 && !instanceId && !alertId) return toast.error("请提供至少 20 个字符的脱敏上下文，或选择已登记实例 / 告警"); analyze.mutate({ context: context.trim() || undefined, instanceId: instanceId ? Number(instanceId) : undefined, alertId: alertId ? Number(alertId) : undefined }); };
  return <div className="mx-auto max-w-[1400px] space-y-6"><PageHeader eyebrow="ASSISTED RESPONSE · D04" title="智能故障处置助手" description="将脱敏的告警、指标、执行日志与实例上下文转化为可审阅的根因分析、风险说明、建议步骤和 Runbook 草案。" />
    <div className="grid gap-4 xl:grid-cols-[.9fr_1.1fr]"><TechCard label="DIAGNOSIS CONTEXT"><div className="flex items-start gap-3"><BrainCircuit className="mt-0.5 h-5 w-5 text-cyan-200" /><div><h2 className="font-display text-lg font-semibold text-white">提交诊断上下文</h2><p className="mt-1 text-xs leading-5 text-blue-100/55">可选择平台内告警或实例，系统会自动拼装相关风险、执行单与脱敏日志；不会要求或传递口令、连接串、私钥。</p></div></div><label className="mt-5 block"><span className="mono text-[10px] uppercase tracking-[.12em] text-blue-100/55">关联告警（可选）</span><select value={alertId} onChange={event => setAlertId(event.target.value)} className="mt-1.5 h-9 w-full border border-blue-200/20 bg-[#071e57] px-3 text-sm text-blue-50"><option value="">不关联告警</option>{(alerts.data ?? []).map(item => <option key={item.id} value={item.id}>[{item.severity}] {item.title}</option>)}</select></label><label className="mt-4 block"><span className="mono text-[10px] uppercase tracking-[.12em] text-blue-100/55">关联实例（可选）</span><select value={instanceId} onChange={event => setInstanceId(event.target.value)} className="mt-1.5 h-9 w-full border border-blue-200/20 bg-[#071e57] px-3 text-sm text-blue-50"><option value="">不关联实例</option>{(assets.data ?? []).map(item => <option key={item.id} value={item.id}>{item.name} · {item.engine}</option>)}</select></label><label className="mt-4 block"><span className="mono text-[10px] uppercase tracking-[.12em] text-blue-100/55">补充告警 / 指标 / 日志上下文</span><textarea value={context} onChange={event => setContext(event.target.value)} placeholder="示例：过去 15 分钟连接数从 180 上升到 920，应用超时率 4.2%，执行日志显示连接池未归还..." className="mt-1.5 min-h-48 w-full border border-blue-200/20 bg-[#071e57] p-3 text-sm leading-6 text-blue-50 placeholder:text-blue-100/30 outline-none focus:border-cyan-200/55" /></label><Button onClick={submit} disabled={analyze.isPending} className="mt-4 w-full gap-2 bg-cyan-200 text-[#061b51] hover:bg-cyan-100">{analyze.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}生成结构化诊断</Button><p className="mt-3 text-center text-[11px] leading-5 text-blue-100/45">使用 gpt-5 服务端模型，仅在您主动点击生成时调用。</p></TechCard>
      <TechCard label="ANALYSIS OUTPUT">{result ? <AnalysisOutput result={result} onCreate={() => createRunbook.mutate({ title: result.runbookDraft.title, category: result.runbookDraft.category, description: `由智能诊断生成：${result.rootCause}`, compatibleEngines: result.runbookDraft.compatibleEngines as never, riskLevel: result.runbookDraft.riskLevel, approvalRequired: result.runbookDraft.approvalRequired, status: "active", steps: result.runbookDraft.steps })} creating={createRunbook.isPending} /> : <div className="flex min-h-[480px] flex-col items-center justify-center border border-dashed border-blue-300/20 p-8 text-center"><Bot className="h-9 w-9 text-cyan-200/55" /><h2 className="mt-4 font-display text-lg font-semibold text-white">等待诊断上下文</h2><p className="mt-2 max-w-sm text-xs leading-6 text-blue-100/55">系统会自动纳入所选实例的健康、容量风险、近期执行单和脱敏日志；任何高风险动作都会明确标记为需要人工确认，且不会自动在生产环境执行。</p></div>}</TechCard></div>
  </div>;
}
function AnalysisOutput({ result, onCreate, creating }: { result: Analysis; onCreate: () => void; creating: boolean }) { return <div><div className="flex items-start justify-between gap-4"><div><p className="mono text-[10px] tracking-[.15em] text-cyan-200">ROOT CAUSE HYPOTHESIS</p><h2 className="mt-2 font-display text-xl font-semibold text-white">{result.rootCause}</h2></div><span className="mono border border-cyan-200/30 bg-cyan-200/10 px-2 py-1 text-xs text-cyan-100">置信度 {Math.round(result.confidence * 100)}%</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Note title="影响面" body={result.impact} /><Note title="风险说明" body={result.risk} /></div><Section title="证据链" items={result.evidence} icon={CheckCircle2} /><Section title="建议处置步骤" items={result.recommendations} icon={ShieldAlert} /><section className="mt-5 border-t border-blue-300/15 pt-4"><div className="flex items-start justify-between gap-4"><div><p className="mono text-[10px] tracking-[.14em] text-cyan-200">STRUCTURED RUNBOOK DRAFT</p><h3 className="mt-2 text-sm font-medium text-white">{result.runbookDraft.title}</h3><p className="mono mt-1 text-[10px] text-blue-100/50">{result.runbookDraft.category} · {result.runbookDraft.riskLevel} · {result.runbookDraft.compatibleEngines.join(", ")}</p></div><Button onClick={onCreate} disabled={creating} size="sm" className="shrink-0 bg-cyan-200 text-[#061b51] hover:bg-cyan-100">{creating ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : "创建 Runbook"}</Button></div><div className="mt-3 space-y-2">{result.runbookDraft.steps.map((step, index) => <div key={`${step.action}-${index}`} className="flex gap-2 text-xs leading-5 text-blue-100/70"><Bot className="mt-0.5 h-3.5 w-3.5 shrink-0 text-cyan-200" /><span><strong className="font-medium text-blue-50">{step.name}</strong> · {step.action}{step.requiresConfirmation ? " · 需确认" : ""}</span></div>)}</div></section><div className={`mt-5 border p-3 text-xs leading-5 ${result.requiresHumanConfirmation ? "border-amber-100/30 bg-amber-100/8 text-amber-50" : "border-cyan-200/25 bg-cyan-200/8 text-cyan-100"}`}><ShieldAlert className="mr-2 inline h-4 w-4" />{result.requiresHumanConfirmation ? "该建议涉及可能影响生产的动作，必须转为 Runbook 后由授权人员确认。" : "该建议仍应按既有变更流程评审，平台不会自动执行。"}</div></div>; }
function Note({ title, body }: { title: string; body: string }) { return <div className="border-l border-cyan-200/35 px-3"><p className="mono text-[10px] tracking-[.12em] text-cyan-200">{title}</p><p className="mt-2 text-xs leading-5 text-blue-100/70">{body}</p></div>; }
function Section({ title, items, icon: Icon }: { title: string; items: string[]; icon: typeof Bot }) { return <section className="mt-5 border-t border-blue-300/15 pt-4"><p className="mono text-[10px] tracking-[.14em] text-cyan-200">{title}</p><div className="mt-3 space-y-2">{items.map((item, index) => <div key={`${title}-${index}`} className="flex gap-2 text-xs leading-5 text-blue-100/70"><Icon className="mt-0.5 h-3.5 w-3.5 shrink-0 text-cyan-200" />{item}</div>)}</div></section>; }
