import { PageHeader, StatusPill, TechCard } from "@/components/Blueprint";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Cable, CheckCircle2, ExternalLink, Loader2, RadioTower, ServerCog } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const integrationInfo: Record<string, { title: string; subtitle: string; data: string }> = { zabbix: { title: "Zabbix", subtitle: "告警事件、主机状态与历史指标", data: "API 引用 + 告警映射" }, prometheus: { title: "Prometheus", subtitle: "PromQL 指标、趋势与容量风险", data: "查询端点 + 标签映射" }, xxl_job: { title: "XXL-Job", subtitle: "调度任务、执行状态与回调结果", data: "执行器标识 + 日志映射" } };

export default function Integrations() {
  const utils = trpc.useUtils(); const integrations = trpc.ops.integrations.list.useQuery(); const nodes = trpc.ops.executors.list.useQuery(); const metrics = trpc.ops.metrics.recent.useQuery();
  const defaultMapping = "{\n  \"instanceId\": \"labels.instanceId\",\n  \"severity\": \"labels.severity\"\n}";
  const [iForm, setIForm] = useState({ name: "", provider: "zabbix", endpoint: "", secretRef: "", mapping: defaultMapping }); const [nForm, setNForm] = useState({ name: "", nodeKey: "", endpoint: "", zone: "", engines: "mysql,postgresql" });
  const addIntegration = trpc.ops.integrations.create.useMutation({ onSuccess: () => { toast.success("集成入口已登记；请在密钥管理系统中配置对应引用"); setIForm({ name: "", provider: "zabbix", endpoint: "", secretRef: "", mapping: defaultMapping }); utils.ops.integrations.list.invalidate(); utils.ops.overview.invalidate(); }, onError: error => toast.error(error.message) });
  const addNode = trpc.ops.executors.register.useMutation({ onSuccess: () => { toast.success("执行节点已登记，等待身份验证与心跳确认"); setNForm({ name: "", nodeKey: "", endpoint: "", zone: "", engines: "mysql,postgresql" }); utils.ops.executors.list.invalidate(); utils.ops.overview.invalidate(); }, onError: error => toast.error(error.message) });
  const submitIntegration = (event: FormEvent) => { event.preventDefault(); try { addIntegration.mutate({ name: iForm.name, provider: iForm.provider as "zabbix" | "prometheus" | "xxl_job", endpoint: iForm.endpoint, secretRef: iForm.secretRef || undefined, mapping: JSON.parse(iForm.mapping) }); } catch { toast.error("字段映射必须是有效 JSON"); } };
  const submitNode = (event: FormEvent) => { event.preventDefault(); const supportedEngines = nForm.engines.split(",").map(item => item.trim()).filter(Boolean); addNode.mutate({ name: nForm.name, nodeKey: nForm.nodeKey, endpoint: nForm.endpoint || undefined, zone: nForm.zone || undefined, environment: "production", capabilities: ["runbook_dispatch", "signed_callback", "masked_logging"], supportedEngines: supportedEngines as never }); };
  return <div className="mx-auto max-w-[1600px] space-y-6"><PageHeader eyebrow="INTEGRATION FABRIC · C03" title="监控、调度与受控执行节点" description="在统一入口登记 Zabbix、Prometheus、XXL-Job 和执行节点。敏感令牌始终以密钥引用方式提供给服务端或节点。" />
    <div className="grid gap-4 md:grid-cols-3">{Object.entries(integrationInfo).map(([provider, info]) => { const saved = integrations.data?.find(item => item.provider === provider); return <TechCard key={provider} label={provider.toUpperCase()}><div className="flex items-start justify-between"><RadioTower className="h-5 w-5 text-cyan-200" />{saved ? <StatusPill status={saved.status} /> : <span className="mono text-[10px] text-blue-100/45">NOT CONFIGURED</span>}</div><h2 className="mt-5 font-display text-lg font-semibold text-white">{info.title}</h2><p className="mt-2 text-xs leading-5 text-blue-100/60">{info.subtitle}</p><p className="mono mt-4 text-[10px] tracking-wider text-cyan-200/70">{info.data}</p></TechCard>; })}</div>
    <div className="grid gap-4 xl:grid-cols-2"><TechCard label="REGISTER INTEGRATION"><h2 className="font-display text-lg font-semibold text-white">登记外部系统</h2><form onSubmit={submitIntegration} className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="集成名称" value={iForm.name} setValue={value => setIForm({ ...iForm, name: value })} required /><Select label="提供方" value={iForm.provider} setValue={value => setIForm({ ...iForm, provider: value })}>{Object.entries(integrationInfo).map(([key, value]) => <option key={key} value={key}>{value.title}</option>)}</Select><div className="sm:col-span-2"><Field label="API / 查询端点" value={iForm.endpoint} setValue={value => setIForm({ ...iForm, endpoint: value })} placeholder="https://monitor.example.com/api" required /></div><div className="sm:col-span-2"><Field label="服务端密钥引用" value={iForm.secretRef} setValue={value => setIForm({ ...iForm, secretRef: value })} placeholder="例如：vault://ops/zabbix/api-token" /></div><label className="sm:col-span-2"><span className="mono text-[10px] uppercase tracking-[.12em] text-blue-100/55">字段映射（JSON）</span><textarea value={iForm.mapping} onChange={event => setIForm({ ...iForm, mapping: event.target.value })} className="mono mt-1.5 min-h-24 w-full border border-blue-200/20 bg-[#071e57] p-3 text-xs leading-5 text-blue-50 outline-none focus:border-cyan-200/55" /></label><Button disabled={addIntegration.isPending} type="submit" className="sm:col-span-2 gap-2 bg-cyan-200 text-[#061b51] hover:bg-cyan-100">{addIntegration.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Cable className="h-4 w-4" />}登记集成入口</Button></form></TechCard>
      <TechCard label="REGISTER EXECUTOR"><h2 className="font-display text-lg font-semibold text-white">登记受控执行节点</h2><form onSubmit={submitNode} className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="节点名称" value={nForm.name} setValue={value => setNForm({ ...nForm, name: value })} required /><Field label="节点标识" value={nForm.nodeKey} setValue={value => setNForm({ ...nForm, nodeKey: value })} placeholder="node-prod-north-01" required /><Field label="节点回调端点" value={nForm.endpoint} setValue={value => setNForm({ ...nForm, endpoint: value })} placeholder="https://gateway.internal" /><Field label="网络区域" value={nForm.zone} setValue={value => setNForm({ ...nForm, zone: value })} placeholder="华北生产区" /><div className="sm:col-span-2"><Field label="支持引擎" value={nForm.engines} setValue={value => setNForm({ ...nForm, engines: value })} placeholder="mysql,postgresql,dameng" required /></div><Button disabled={addNode.isPending} type="submit" className="sm:col-span-2 gap-2 bg-cyan-200 text-[#061b51] hover:bg-cyan-100">{addNode.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <ServerCog className="h-4 w-4" />}登记节点</Button></form></TechCard></div>
    <div className="grid gap-4 xl:grid-cols-2"><TechCard label="CONFIGURED SYSTEMS"><h2 className="font-display text-lg font-semibold text-white">已登记集成</h2><div className="mt-4 space-y-3">{(integrations.data ?? []).map(item => <div key={item.id} className="flex items-center justify-between gap-3 border-b border-blue-300/12 pb-3 last:border-0"><div><p className="text-sm text-white">{item.name}</p><p className="mono mt-1 text-[10px] text-blue-100/45">{item.provider} · {item.endpoint}</p></div><StatusPill status={item.status} /></div>)}{!integrations.data?.length ? <p className="text-sm text-blue-100/50">尚未登记集成入口。</p> : null}</div></TechCard><TechCard label="EXECUTION NODES"><h2 className="font-display text-lg font-semibold text-white">受控执行节点</h2><div className="mt-4 space-y-3">{(nodes.data ?? []).map(item => <div key={item.id} className="flex items-center justify-between gap-3 border-b border-blue-300/12 pb-3 last:border-0"><div><p className="text-sm text-white">{item.name}</p><p className="mono mt-1 text-[10px] text-blue-100/45">{item.nodeKey} · {item.zone ?? "UNASSIGNED ZONE"}</p></div><StatusPill status={item.status} /></div>)}{!nodes.data?.length ? <p className="text-sm text-blue-100/50">尚未登记受控执行节点。</p> : null}</div></TechCard></div>
    <TechCard label="RECENT METRICS"><div className="flex items-end justify-between gap-3"><div><h2 className="font-display text-lg font-semibold text-white">近期监控指标</h2><p className="mt-1 text-xs text-blue-100/55">展示由 Zabbix 或 Prometheus 字段映射后回传的最近 30 条指标快照。</p></div><p className="mono text-xs text-cyan-200">{metrics.data?.length ?? 0} SAMPLES</p></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead className="mono border-y border-blue-300/15 text-[10px] uppercase tracking-[.12em] text-blue-100/45"><tr><th className="px-3 py-3 font-medium">指标</th><th className="px-3 py-3 font-medium">值</th><th className="px-3 py-3 font-medium">实例</th><th className="px-3 py-3 font-medium">标签</th></tr></thead><tbody>{(metrics.data ?? []).map(item => <tr key={item.id} className="border-b border-blue-300/10 text-xs text-blue-100/70"><td className="px-3 py-3 text-white">{item.metric}</td><td className="mono px-3 py-3 text-cyan-100">{item.value} {item.unit ?? ""}</td><td className="mono px-3 py-3">{item.instanceId ?? "UNMAPPED"}</td><td className="mono max-w-72 truncate px-3 py-3 text-[10px]">{JSON.stringify(item.labels ?? {})}</td></tr>)}{!metrics.data?.length ? <tr><td colSpan={4} className="py-10 text-center text-sm text-blue-100/50">暂无指标快照。配置外部系统后，将指标数组回传至相应接收端点。</td></tr> : null}</tbody></table></div></TechCard>
    <div className="grid gap-4 xl:grid-cols-2"><div className="flex gap-3 border border-blue-300/15 bg-blue-200/5 p-4 text-xs leading-5 text-blue-100/60"><CheckCircle2 className="h-4 w-4 shrink-0 text-cyan-200" /><p>建议的接入流程为：先配置密钥引用，再通过网络白名单和双向认证验证执行节点；节点仅可拉取已确认的执行单，并以签名回调返回脱敏执行日志与结构化结果。</p></div><div className="border border-cyan-200/20 bg-cyan-200/5 p-4 text-xs leading-5 text-blue-100/70"><p className="mono text-[10px] tracking-[.13em] text-cyan-200">INBOUND EVENT CONTRACT</p><p className="mt-2">事件端点：<code className="text-cyan-100">POST /api/integrations/ingest/zabbix</code>、<code className="text-cyan-100">/prometheus</code>、<code className="text-cyan-100">/xxl_job</code>。所有回调均应带 <code className="text-cyan-100">x-integration-secret</code>。</p></div></div>
  </div>;
}
function Field({ label, value, setValue, placeholder, required }: { label: string; value: string; setValue: (value: string) => void; placeholder?: string; required?: boolean }) { return <label><span className="mono text-[10px] uppercase tracking-[.12em] text-blue-100/55">{label}</span><Input value={value} onChange={event => setValue(event.target.value)} placeholder={placeholder} required={required} className="mt-1.5 border-blue-200/20 bg-[#071e57] text-blue-50 placeholder:text-blue-100/30" /></label>; }
function Select({ label, value, setValue, children }: { label: string; value: string; setValue: (value: string) => void; children: React.ReactNode }) { return <label><span className="mono text-[10px] uppercase tracking-[.12em] text-blue-100/55">{label}</span><select value={value} onChange={event => setValue(event.target.value)} className="mt-1.5 h-9 w-full border border-blue-200/20 bg-[#071e57] px-3 text-sm text-blue-50">{children}</select></label>; }
