- name: Transfer sql statement to remonte
  ansible.builtin.template:
    src: ../templates/config_group_replication.sql.j2
    dest: /tmp/config_group_replication.sql
    mode: '0600'

- name: Config mysql group replication
  ansible.builtin.shell: >
    {{ mysql_software_dir }}/bin/mysql -hlocalhost -u{{ mysql_admin_user }} -p{{ mysql_admin_password }} -S {{ socket }} < /tmp/config_group_replication.sql
  changed_when: true

- name: Remove temp file /tmp/config_group_replication.sql
  ansible.builtin.file:
    dest: "/tmp/config_group_replication.sql"
    state: absent
