type AlertSeverity = "critical" | "high" | "medium" | "low" | "info";
type AlertStatus = "open" | "acknowledged" | "resolved";
type ExecutionStatus = "queued" | "dispatched" | "running" | "succeeded" | "failed" | "cancelled";

export type IntegrationMapping = Record<string, unknown> & { alerts?: Record<string, string>; metrics?: Record<string, string>; tasks?: Record<string, string> };
export type NormalizedAlert = { externalId?: string; title: string; severity: AlertSeverity; status: AlertStatus; metric?: string; currentValue?: string; threshold?: string; instanceId?: number; context: Record<string, unknown> };
export type NormalizedMetric = { metric: string; value: string; unit?: string; instanceId?: number; labels: Record<string, unknown> };
export type NormalizedTask = { executionKey: string; status: ExecutionStatus; message?: string; result?: Record<string, unknown> };

function asRecord(value: unknown) { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function text(value: unknown, fallback: string) { return typeof value === "string" && value.trim() ? value.trim().slice(0, 255) : fallback; }
function optionalId(value: unknown) { const id = typeof value === "number" ? value : Number(value); return Number.isInteger(id) && id > 0 ? id : undefined; }
function readPath(input: unknown, path: unknown): unknown { if (typeof path !== "string" || !path.trim()) return undefined; return path.split(".").reduce<unknown>((value, part) => value && typeof value === "object" && !Array.isArray(value) ? (value as Record<string, unknown>)[part] : undefined, input); }
function mapped(source: unknown, mapping: IntegrationMapping, group: "alerts" | "metrics" | "tasks", key: string, fallback: unknown) { const groupMap = asRecord(mapping[group]); const path = typeof groupMap[key] === "string" ? groupMap[key] : typeof mapping[key] === "string" ? mapping[key] : undefined; return readPath(source, path) ?? fallback; }

const severityBySource: Record<string, AlertSeverity> = { disaster: "critical", critical: "critical", high: "high", warning: "medium", average: "medium", medium: "medium", minor: "low", low: "low", information: "info", info: "info" };
function normalizeSeverity(value: unknown): AlertSeverity { return severityBySource[String(value ?? "").toLowerCase()] ?? "medium"; }
function normalizeAlertStatus(value: unknown): AlertStatus { const status = String(value ?? "").toLowerCase(); return ["resolved", "ok", "recovered"].includes(status) ? "resolved" : status === "acknowledged" ? "acknowledged" : "open"; }
function normalizeExecutionStatus(value: unknown): ExecutionStatus { const status = String(value ?? "").toLowerCase(); return ["queued", "dispatched", "running", "succeeded", "failed", "cancelled"].includes(status) ? status as ExecutionStatus : "failed"; }
function normalizeMetrics(raw: unknown, mapping: IntegrationMapping): NormalizedMetric[] { return Array.isArray(raw) ? raw.map((entry, index) => { const item = asRecord(entry); return { metric: text(mapped(item, mapping, "metrics", "metric", item.metric ?? item.name), `metric_${index}`), value: String(mapped(item, mapping, "metrics", "value", item.value ?? item.currentValue ?? "0")).slice(0, 128), unit: typeof mapped(item, mapping, "metrics", "unit", item.unit) === "string" ? String(mapped(item, mapping, "metrics", "unit", item.unit)).slice(0, 32) : undefined, instanceId: optionalId(mapped(item, mapping, "metrics", "instanceId", item.instanceId)), labels: asRecord(mapped(item, mapping, "metrics", "labels", item.labels)) }; }) : []; }

export function normalizeIntegrationPayload(provider: string, body: unknown, mapping: IntegrationMapping = {}): { alerts: NormalizedAlert[]; metrics: NormalizedMetric[]; tasks: NormalizedTask[] } {
  const payload = asRecord(body);
  if (!Object.keys(payload).length) throw new Error("integration payload must be a JSON object");
  if (provider === "prometheus") {
    const alerts = Array.isArray(payload.alerts) ? payload.alerts.map((entry, index) => { const item = asRecord(entry); const labels = asRecord(item.labels); const annotations = asRecord(item.annotations); return { externalId: text(mapped(item, mapping, "alerts", "externalId", labels.fingerprint ?? labels.alertname ?? `${index}`), `prometheus-${index}`), title: text(mapped(item, mapping, "alerts", "title", annotations.summary ?? annotations.description ?? labels.alertname), "Prometheus 告警"), severity: normalizeSeverity(mapped(item, mapping, "alerts", "severity", labels.severity)), status: normalizeAlertStatus(mapped(item, mapping, "alerts", "status", item.status)), metric: text(mapped(item, mapping, "alerts", "metric", labels.alertname), "alertname"), currentValue: typeof mapped(item, mapping, "alerts", "currentValue", annotations.value) === "string" ? String(mapped(item, mapping, "alerts", "currentValue", annotations.value)) : undefined, instanceId: optionalId(mapped(item, mapping, "alerts", "instanceId", labels.instanceId)), context: { labels, annotations, startsAt: item.startsAt, endsAt: item.endsAt } }; }) : [];
    return { alerts, metrics: normalizeMetrics(payload.metrics, mapping), tasks: [] };
  }
  if (provider === "zabbix") return { alerts: [{ externalId: typeof mapped(payload, mapping, "alerts", "externalId", payload.eventid ?? payload.eventId) === "string" ? String(mapped(payload, mapping, "alerts", "externalId", payload.eventid ?? payload.eventId)) : undefined, title: text(mapped(payload, mapping, "alerts", "title", payload.subject ?? payload.title ?? payload.message), "Zabbix 告警"), severity: normalizeSeverity(mapped(payload, mapping, "alerts", "severity", payload.severity)), status: normalizeAlertStatus(mapped(payload, mapping, "alerts", "status", payload.status ?? payload.eventStatus)), metric: typeof mapped(payload, mapping, "alerts", "metric", payload.metric) === "string" ? String(mapped(payload, mapping, "alerts", "metric", payload.metric)) : undefined, currentValue: typeof mapped(payload, mapping, "alerts", "currentValue", payload.currentValue) === "string" ? String(mapped(payload, mapping, "alerts", "currentValue", payload.currentValue)) : undefined, threshold: typeof mapped(payload, mapping, "alerts", "threshold", payload.threshold) === "string" ? String(mapped(payload, mapping, "alerts", "threshold", payload.threshold)) : undefined, instanceId: optionalId(mapped(payload, mapping, "alerts", "instanceId", payload.instanceId)), context: payload }], metrics: normalizeMetrics(payload.metrics, mapping), tasks: [] };
  if (provider === "xxl_job") { const executionKey = text(mapped(payload, mapping, "tasks", "executionKey", payload.executionKey ?? payload.runbookExecutionKey), ""); if (!executionKey) throw new Error("XXL-Job payload requires executionKey or runbookExecutionKey"); return { alerts: [], metrics: [], tasks: [{ executionKey, status: normalizeExecutionStatus(mapped(payload, mapping, "tasks", "status", payload.status ?? payload.taskStatus)), message: typeof mapped(payload, mapping, "tasks", "message", payload.message) === "string" ? String(mapped(payload, mapping, "tasks", "message", payload.message)).slice(0, 4000) : undefined, result: asRecord(mapped(payload, mapping, "tasks", "result", payload.result)) }] }; }
  throw new Error("unsupported integration provider");
}
