import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { startLogin } from "@/const";
import { Activity, KeyRound, Loader2, LockKeyhole, ShieldCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

export function LocalLoginGate() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [pending, setPending] = useState(false);
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setPending(true);
    try {
      const response = await fetch("/api/local-auth/login", { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ username, password }) });
      const result = await response.json() as { ok: boolean; error?: string };
      if (!response.ok || !result.ok) throw new Error(result.error ?? "本地登录失败");
      window.location.assign("/");
    } catch (error) { toast.error(error instanceof Error ? error.message : "本地登录失败"); } finally { setPending(false); }
  };
  return <div className="blueprint-canvas flex min-h-screen items-center justify-center p-5"><div className="tech-card w-full max-w-md p-7 sm:p-8"><div className="flex flex-col items-center text-center"><Activity className="h-8 w-8 text-cyan-200" /><p className="mono mt-4 text-[10px] tracking-[.2em] text-cyan-200">DB CONTROL · SECURE ACCESS</p><h1 className="mt-3 font-display text-2xl font-semibold text-white">进入数据库运维中心</h1><p className="mt-3 text-sm leading-6 text-blue-100/60">使用本地初始化管理员凭据登录，或继续使用现有安全账号授权。</p></div><form onSubmit={submit} className="mt-7 space-y-4"><label><span className="mono text-[10px] tracking-[.14em] text-blue-100/55">初始化管理员用户名</span><Input value={username} onChange={event => setUsername(event.target.value)} autoComplete="username" required className="mt-1.5 border-blue-200/20 bg-[#071e57] text-blue-50" /></label><label><span className="mono text-[10px] tracking-[.14em] text-blue-100/55">临时密码</span><Input value={password} onChange={event => setPassword(event.target.value)} type="password" autoComplete="current-password" required className="mt-1.5 border-blue-200/20 bg-[#071e57] text-blue-50" /></label><Button type="submit" disabled={pending} className="w-full gap-2 bg-cyan-200 text-[#061b51] hover:bg-cyan-100">{pending ? <Loader2 className="h-4 w-4 animate-spin" /> : <KeyRound className="h-4 w-4" />}本地安全登录</Button></form><div className="my-6 flex items-center gap-3 text-[10px] text-blue-100/35"><span className="h-px flex-1 bg-blue-200/15" />或<span className="h-px flex-1 bg-blue-200/15" /></div><Button onClick={() => startLogin()} variant="outline" className="w-full gap-2 border-blue-200/25 text-blue-50 hover:bg-blue-200/10"><ShieldCheck className="h-4 w-4" />使用安全账号登录</Button><p className="mt-5 flex items-start gap-2 text-xs leading-5 text-blue-100/45"><LockKeyhole className="mt-0.5 h-3.5 w-3.5 shrink-0 text-cyan-200" />本地初始化账号首次登录后必须修改密码，完成前无法访问资产、执行和审计数据。</p></div></div>;
}

export function PasswordChangeGate({ username, onComplete }: { username: string; onComplete: () => void }) {
  const [currentPassword, setCurrentPassword] = useState(""); const [nextPassword, setNextPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [pending, setPending] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (nextPassword !== confirmPassword) return toast.error("两次输入的新密码不一致"); setPending(true); try { const response = await fetch("/api/local-auth/change-password", { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ currentPassword, nextPassword }) }); const result = await response.json() as { ok: boolean; error?: string }; if (!response.ok || !result.ok) throw new Error(result.error ?? "密码修改失败"); toast.success("密码已更新，正在进入控制台"); onComplete(); } catch (error) { toast.error(error instanceof Error ? error.message : "密码修改失败"); } finally { setPending(false); } };
  return <div className="blueprint-canvas flex min-h-screen items-center justify-center p-5"><div className="tech-card w-full max-w-md p-7 sm:p-8"><div className="flex flex-col items-center text-center"><KeyRound className="h-8 w-8 text-amber-200" /><p className="mono mt-4 text-[10px] tracking-[.2em] text-amber-200">FIRST ACCESS · PASSWORD ROTATION</p><h1 className="mt-3 font-display text-2xl font-semibold text-white">请先修改初始密码</h1><p className="mt-3 text-sm leading-6 text-blue-100/60">管理员 <strong className="text-blue-50">{username}</strong>，此账户在完成密码更新前不能使用运维控制台。</p></div><form onSubmit={submit} className="mt-7 space-y-4"><label><span className="mono text-[10px] tracking-[.14em] text-blue-100/55">当前临时密码</span><Input value={currentPassword} onChange={event => setCurrentPassword(event.target.value)} type="password" autoComplete="current-password" required className="mt-1.5 border-blue-200/20 bg-[#071e57] text-blue-50" /></label><label><span className="mono text-[10px] tracking-[.14em] text-blue-100/55">新密码</span><Input value={nextPassword} onChange={event => setNextPassword(event.target.value)} type="password" autoComplete="new-password" minLength={16} required className="mt-1.5 border-blue-200/20 bg-[#071e57] text-blue-50" /></label><label><span className="mono text-[10px] tracking-[.14em] text-blue-100/55">确认新密码</span><Input value={confirmPassword} onChange={event => setConfirmPassword(event.target.value)} type="password" autoComplete="new-password" minLength={16} required className="mt-1.5 border-blue-200/20 bg-[#071e57] text-blue-50" /></label><p className="text-xs leading-5 text-blue-100/45">至少 16 位，且包含大写字母、小写字母、数字和特殊字符。</p><Button type="submit" disabled={pending} className="w-full gap-2 bg-amber-200 text-[#261700] hover:bg-amber-100">{pending ? <Loader2 className="h-4 w-4 animate-spin" /> : <LockKeyhole className="h-4 w-4" />}更新密码并继续</Button></form></div></div>;
}
